- platform: template
  sensors:
    livingroom_last_movement_time:
      value_template: "{{as_timestamp(states.binary_sensor.motion_sensor_livingroom.last_changed) | timestamp_custom('%A %d-%b-%y, %H:%M:%S')}}"