- platform: template
  sensors:
    bedroom_bed_motion_sensor_right_last_occured:
      value_template: "{{as_timestamp(states.binary_sensor.bedroom_bed_motion_sensor_right.last_changed) | timestamp_custom('%A %d-%b-%y, %H:%M:%S')}}"