- alias: "Stefan's iPhone is charging"
  initial_state: true
  trigger:
    - platform: event
      event_type: ios.action_fired
      event_data:
        actionName: 'Connected to charger'
  action:
    - service: input_boolean.turn_on
      entity_id: input_boolean.charging_stefans_iphone
    - service: script.turn_off
      entity_id: script.low_battery_iphone 

- alias: "Stefan's iPhone is not charging"
  initial_state: true
  trigger:
    - platform: event
      event_type: ios.action_fired
      event_data:
        actionName: 'Disconnected from charger'
  action:
    service: input_boolean.turn_off
    entity_id: input_boolean.charging_stefans_iphone