- alias: Bathroom turn on boiler at cheapest tarif
  trigger:
    - platform: time
      at: input_datetime.time_when_boiler_goes_to_on
  action:
      service: switch.turn_on
      entity_id: switch.bathroom_boiler

- alias: Bathroom turn off boiler at non_cheapest tarif
  trigger:
    - platform: time
      at: input_datetime.time_when_boiler_goes_to_off
  action:
      service: switch.turn_off
      entity_id: switch.bathroom_boiler