- alias: 'control fan by humidity'
  trigger:
    - platform: numeric_state
      entity_id: sensor.bathroom_humidity
      above: 60  
  action:
    - service_template: >
        {% if states('sensor.bathroom_humidity') | float >= 60 %}
          switch.turn_on
        {% else %}
          switch.turn_off
        {% endif %}
      entity_id: switch.bathroom_fan