- alias: Turn on and set Bedroom TV
  description: 'Sets EON for Bedroom TV when turns on'
  trigger:
    - platform: state
      entity_id: media_player.bedroom_tv
      to: 'on'
  action:
    #- delay: "00:00:10"
    - wait_template: "{{ is_state('media_player.bedroom_tv','on') }}"
      timeout: '00:01:00'
      continue_on_timeout: 'true'
    - service: braviatv_psk.bravia_open_app
      data:
        entity_id: media_player.bedroom_bravia
        uri: >-
          com.sony.dtv.com.ug.eon.android.tv.com.ug.eon.android.tv.TvActivity