- alias: Toggle unobtrusive mode
  trigger:
    - platform: time
      at: "00:30:00"
    - platform: time
      at: "07:30:00"
  action:
    - service_template: >
        {% if now().hour == 0 and now().minute == 30 and now().second == 0 %}
          input_boolean.turn_on
        {% elif now().hour == 7 and now().minute == 30 and now().second == 0 %}
          input_boolean.turn_off
        {% else %}
          #DoNothing
        {% endif %}
      entity_id: input_boolean.unobtrusive_mode