#SINGLE SHORT CLICK

- alias: Hallway Wardrobe Ledstrip Short Button
  id: hallway_wardrobe_ledstrip_short_button
  trigger:
    platform: event
    event_type: esphome.hallway
    event_data:
      type: single_short_click_2
  action:
    - service: light.toggle
      entity_id: light.hallway_wled
      data:
        effect: 'solid'
        rgb_color: [255,212,138]
        brightness: 255

#SINGLE LONG CLICK

- alias: Hallway Wardrobe_Ledstrip Long Click
  id: hallway_wardrobe_ledstrip_single_long_click
  trigger:
    platform: event
    event_type: esphome.hallway
    event_data:
      type: single_long_click_2
  action:
    - service: light.turn_on
      entity_id: light.hallway_wled
      data:
        effect: 'solid'

#DOUBLE CLICK

- alias: Hallway Actuator Double Click
  id:  hallway_actuator_double_click
  trigger:
    platform: event
    event_type: esphome.hallway
    event_data:
      type: double_click_2
  action:
    - service: script.turn_on
      entity_id: script.wled_random
      data:
        variables:
          wled: light.hallway_wled

#ROTARY ENCODER

- alias: 'Hallway Wardrobe Ledstrip Dimmer'
  id: hallway_wardrobe_ledstrip_dimmer
  trigger:
    - platform: state
      entity_id: sensor.hallway_ledstrip_encoder
  action:
    - choose:
        - conditions:
            - condition: template
              value_template: "{{ trigger.to_state.state not in ['Unavailable','Unknown'] }}"
          sequence:
            - service: light.turn_on
              entity_id: light.hallway_wled
              data:
                brightness: >
                  {{states('sensor.hallway_ledstrip_encoder') | int * 2.55 | round(0) }}