#SINGLE SHORT CLICK

- alias: Kitchen Terace Spots via encoder
  id: kitchen_terace_spots_via_encoder
  trigger:
    platform: event
    event_type: esphome.kitchen
    event_data:
      type: single_short_click_1
  action:
    - service: persistent_notification.create
      data:
        title: 'This is a Kitchen Terace Spots single short click'
        message: "Test indeed."
    # - service: light.toggle
    #   entity_id: 
    #     - light.bedroom_go_temperature_wall
    #     - light.bedroom_go_color_wall

- alias: Kitchen Terace Ledstrip toggle via encoder
  id: kitchen_terace_ledstrip_short_click
  trigger:
    platform: event
    event_type: esphome.kitchen
    event_data:
      type: single_short_click_2
  action:
    - service: light.toggle
      entity_id:
        - light.livingroom_go_temp_teracewall
        - light.livingroom_go_color_teracewall

- alias: Kitchen Workingdesk Light via encoder
  id: kitchen_workingdesk_light_click
  trigger:
    platform: event
    event_type: esphome.kitchen
    event_data:
      type: single_short_click_3
  action:
    - service: light.toggle
      entity_id: light.kitchen_wled

- alias: Kitchen Actuator via encoder
  id: kitchen_actuator_click
  trigger:
    platform: event
    event_type: esphome.kitchen
    event_data:
      type: single_short_click_4
  action:
    - service: script.turn_on
      entity_id: script.watch_tv_livingroom
      data:
        variables:
          tvsource: "SBB"

#SINGLE LONG CLICK

- alias: Kitchen Terace Spots Long Click
  id: kitchen_terace_spots_single_long_click
  trigger:
    platform: event
    event_type: esphome.kitchen
    event_data:
      type: single_long_click_1
  action:
    - service: persistent_notification.create
      data:
        title: 'This is a Kitchen short click 1 test'
        message: "Test indeed."
    # - service: light.turn_off
    #   entity_id: 
    #     - light.bedroom_go_temperature_wall
    #     - light.bedroom_go_color_wall

- alias: Kitchen Terace Ledstrip Long Click
  id: kitchen_terace_ledstrip_long_click
  trigger:
    platform: event
    event_type: esphome.kitchen
    event_data:
      type: single_long_click_2
  action:
    - service: light.turn_off
      entity_id: 
        - light.livingroom_go_temp_teracewall
        - light.livingroom_go_color_teracewall

- alias: Kitchen Workdesk Long Click
  id: kitchen_workdesk_long_click
  trigger:
    platform: event
    event_type: esphome.kitchen
    event_data:
      type: single_long_click_3
  action:
    - service: light.turn_off
      entity_id: light.kitchen_wled

- alias: Kitchen Actuator Long Click
  id: kitchen_actuator_long_click
  trigger:
    platform: event
    event_type: esphome.kitchen
    event_data:
      type: single_long_click_4
  action:
    - service: media_player.turn_off
      entity_id: media_player.livingroom_tv

#DOUBLE CLICK

- alias: Kitchen Terace Spots Double Click
  id: kitchen_terace_spots_double_click
  trigger:
    platform: event
    event_type: esphome.kitchen
    event_data:
      type: double_click_1
  action:
    - service: persistent_notification.create
      data:
        title: 'This is a Kitchen short click 1 test'
        message: "Test indeed."
    # - service: light.turn_off
    #   entity_id: light.bedroom_go_temperature_wall          
    # - service: light.turn_on
    #   entity_id: light.bedroom_go_color_wall
    #   data:
    #     rgb_color: ["{{range(256)|random}}","{{range(256)|random}}","{{range(256)|random}}"]

- alias: Kitchen Terace Ledstrip Double Click
  id: kitchen_terace_ledstrip_double_click
  trigger:
    platform: event
    event_type: esphome.kitchen
    event_data:
      type: double_click_2
  action:
    - service: light.turn_off
      entity_id: light.livingroom_go_temp_teracewall       
    - service: light.turn_on
      entity_id: light.livingroom_go_color_teracewall
      data:
        rgb_color: ["{{range(256)|random}}","{{range(256)|random}}","{{range(256)|random}}"]

- alias: Kitchen Workdesk Ledstrip Double Click
  id: kitchen_workdesk_ledstrip_double_click
  trigger:
    platform: event
    event_type: esphome.kitchen
    event_data:
      type: double_click_3
  action:
    - service: light.turn_on
      entity_id: light.kitchen_wled
      data:
        rgb_color: ["{{range(256)|random}}","{{range(256)|random}}","{{range(256)|random}}"]

- alias: Kitchen Actuator Double Click
  id: kitchen_actuator_double_click
  trigger:
    platform: event
    event_type: esphome.kitchen
    event_data:
      type: double_click_4
  action:
    # - service: persistent_notification.create
    #   data:
    #     title: 'This is a Kitchen short click 1 test'
    #     message: "Test indeed."
    # - service: switch.turn_on
    #   entity_id: switch.bedroom_led_light_trafo

    # - service: light.turn_off
    #   entity_id: light.bedroom_go_temp_bed       

    # - service: light.turn_on
    #   entity_id: light.bedroom_go_color_bed
    #   data:
    #     rgb_color: ["{{range(256)|random}}","{{range(256)|random}}","{{range(256)|random}}"]

#ROTARY ENCODER

- alias: 'Kitchen Terace Spots Dimmer'
  id: kitchen_terace_spots_dimming_encoder
  trigger:
    - platform: state
      entity_id: sensor.kitchen_terace_spots_dimmer
  action:
    - service: persistent_notification.create
      data:
        title: 'This is a Terace Spots Dimmer encoder dimmer'
        message: "Test indeed."
    # - choose:
    #     - conditions:
    #         - condition: template
    #           value_template: "{{ trigger.to_state.state not in ['Unavailable','Unknown'] }}"
    #       sequence:
    #         - service: light.turn_on
    #           entity_id: light.bedroom_go_temperature_wall
    #           data:
    #             brightness: >
    #               {{states('sensor.kitchen_led_ceiling_dimmer') | int * 2.55 | round(0) }}

- alias: 'Kitchen Terace Ledstrip Dimming via encoder' 
  id: kitchen_terace_ledstrip_dimming_encoder 
  trigger:
    - platform: state
      entity_id: sensor.kitchen_terace_ledstrip_dimmer
  action:
    - choose:
        - conditions:
            - condition: template
              value_template: "{{ trigger.to_state.state not in ['Unavailable','Unknown'] }}"
          sequence:
            - service: light.turn_on
              entity_id: light.livingroom_go_temp_teracewall
              data:
                brightness: >
                  {{states('sensor.kitchen_terace_ledstrip_dimmer') | int }}

- alias: 'Kitchen Workdesk Dimmer'
  id: kitchen_workdesk_dimmer 
  trigger:
    - platform: state
      entity_id: sensor.kitchen_workingdesk_dimmer
  action:
    - choose:
        - conditions:
            - condition: template
              value_template: "{{ trigger.to_state.state not in ['Unavailable','Unknown'] }}"
          sequence:
            - service: light.turn_on
              entity_id: light.kitchen_wled
              data:
                brightness: >
                  {{states('sensor.kitchen_workingdesk_dimmer') | int }}

- alias: 'Kitchen Actuator Encoder'
  id: kitchen_actuator_encoder 
  trigger:
    - platform: state
      entity_id: sensor.kitchen_actuator_encoder
  action:
    - choose:
        - conditions:
            - condition: template
              value_template: "{{ trigger.to_state.state not in ['Unavailable','Unknown'] }}"
          sequence:
            - service: media_player.volume_set
              entity_id: media_player.avr_zone1
              data:
                volume_level: >
                  {{ states('sensor.kitchen_actuator_encoder')|float/100 }}