esphome:
  name: livingroom_entrance_controller_1
  platform: ESP32
  board: wemos_d1_mini32

wifi:
  ssid: "ThePingInTheNorth"
  password: "lanister"
  # ...
  power_save_mode: none
  manual_ip:
    # Set this to the IP of the ESP
    static_ip: 192.168.1.105
    # Set this to the IP address of the router. Often ends with .1
    gateway: 192.168.1.1
    # The subnet of the network. 255.255.255.0 works for most home networks.
    subnet: 255.255.255.0
  

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Livingroom Entrance Controller 1"
    password: "dubai.2020"

captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:

sensor:
  - platform: rotary_encoder
    name: "Livingroom LED AboveTV Dimmer"
    id: livingroom_led_abovetv_dimmer
    pin_a: GPIO32 #GPIO27
    pin_b: GPIO25 #GPIO25
    min_value: 0
    max_value: 100
    resolution: 2
    filters:
      - delta: 4.0
  - platform: rotary_encoder
    name: "Livingroom LED BelowTV Dimmer"
    id: livingroom_led_belowtv_dimmer
    pin_a: GPIO21 #GPIO17
    pin_b: GPIO16
    min_value: 0
    max_value: 100
    resolution: 2
    filters:
      - delta: 4.0
  - platform: rotary_encoder
    name: "Livingroom Actuator Encoder"
    id: livingroom_actuator_encoder
    pin_a: GPIO23 #GPIO19
    pin_b: GPIO34
    min_value: 0
    max_value: 100
    resolution: 2
    filters:
      - delta: 4.0

  - platform: rotary_encoder
    name: "Livingroom Greywall LED Dimmer"
    id: livingroom_greywall_led_dimmer
    pin_a: GPIO19
    pin_b: GPIO18
    min_value: 0
    max_value: 100
    resolution: 2
    filters:
      - delta: 4.0

binary_sensor:
  - platform: gpio
    name: "Livingroom LED AboveTV Switch"
    id: livingroom_led_abovetv_switch
    pin:
      number: GPIO27 #GPIO21
      mode: INPUT_PULLUP
      inverted: true
    on_multi_click:
      - timing:
          - ON for at most 1s
          - OFF for at least 0.5s
        then:
          - homeassistant.event:
              event: esphome.livingroom_entrance_1
              data:
                type: single_short_click_2
      - timing:
          - ON for 1s to 2s
          - OFF for at least 0.5s
        then:
          - homeassistant.event:
              event: esphome.livingroom_entrance_1
              data:
                type: single_long_click_2
      - timing:
          - ON for at most 1s
          - OFF for at most 1s
          - ON for at most 1s
          - OFF for at least 0.2s
        then:
          - homeassistant.event:
              event: esphome.livingroom_entrance_1
              data:
                type: double_click_2
    
  - platform: gpio
    name: "Livingroom LED BelowTV Switch"
    id: livingroom_led_belowtv_switch
    pin:
      number: GPIO17
      mode: INPUT_PULLUP
      inverted: true
    on_multi_click:
      - timing:
          - ON for at most 1s
          - OFF for at least 0.5s
        then:
          - homeassistant.event:
              event: esphome.livingroom_entrance_1
              data:
                type: single_short_click_3
      - timing:
          - ON for 1s to 2s
          - OFF for at least 0.5s
        then:
          - homeassistant.event:
              event: esphome.livingroom_entrance_1
              data:
                type: single_long_click_3
      - timing:
          - ON for at most 1s
          - OFF for at most 1s
          - ON for at most 1s
          - OFF for at least 0.2s
        then:
          - logger.log: "double click below tv"
          - homeassistant.event:
              event: esphome.livingroom_entrance_1
              data:
                type: double_click_3

  - platform: gpio
    name: "Livingroom Actuator Switch"
    id: livingroom_actuator_switch
    pin:
      number: GPIO35 #GPIO18
      mode: INPUT_PULLUP
      inverted: true
    on_multi_click:
      - timing:
          - ON for at most 1s
          - OFF for at least 0.5s
        then:
          - homeassistant.event:
              event: esphome.livingroom_entrance_1
              data:
                type: single_short_click_4
      - timing:
          - ON for 1s to 2s
          - OFF for at least 0.5s
        then:
          - homeassistant.event:
              event: esphome.livingroom_entrance_1
              data:
                type: single_long_click_4
      - timing:
          - ON for at most 1s
          - OFF for at most 1s
          - ON for at most 1s
          - OFF for at least 0.2s
        then:
          - homeassistant.event:
              event: esphome.livingroom_entrance_1
              data:
                type: double_click_4

  - platform: gpio
    name: "Livingroom Greywall LED Switch"
    id: livingroom_greywall_led_switch
    pin:
      number: GPIO26
      mode: INPUT_PULLUP
      inverted: true
    on_multi_click:
      - timing:
          - ON for at most 1s
          - OFF for at least 0.5s
        then:
          - homeassistant.event:
              event: esphome.livingroom_entrance_1
              data:
                type: single_short_click_1
      - timing:
          - ON for 1s to 2s
          - OFF for at least 0.5s
        then:
          - homeassistant.event:
              event: esphome.livingroom_entrance_1
              data:
                type: single_long_click_1
      - timing:
          - ON for at most 1s
          - OFF for at most 1s
          - ON for at most 1s
          - OFF for at least 0.2s
        then:
          - homeassistant.event:
              event: esphome.livingroom_entrance_1
              data:
                type: double_click_1